### PR TITLE
Your BLEConnect doesn't work / implement the standard on Android devices.

### PR DESCRIPTION
**Pull request by glatteis**
Hi,
I opened a pull request (with no further content) because you don't accept issues.
In Android, you do not advertise a Client Characteristic Configuration Descriptor. This means, that one cannot subscribe to notifications of your BLE service, yet this is what you have to do for this to work.
I still haven't gotten it to work on my ESP, but [some people apparently have _modifying the library_ on their end device, so that it accepts your non-standard way of doing things](https://github.com/jstiefel/esp32_komoot_ble/issues/3).
This apparently also breaks any cross-compability you might have with iOS and Android devices.
This involves a lot of unnecessary headache for people who try to use this API, I still haven't figured out how to modify my client. Please fix it in your app, or at least show some kind of response. Thanks!

### CODE REVIEW

**Comment by danielgard** [comment]
Hi @glatteis 

Thanks for your message! 
We tried to develop the interface as close as possible to the existing standards in order to make it work with as many BLE devices as possible. 
 
This is the first time we are facing this problem. A reason might be that partners implementing the protocol are often using custom BLE implementations on their low level devices.

It would be great if you can send me a more detailed explanation what you see and what you would expect so we can take a closer look at our Android implementation and see how we can improve. -> daniel@komoot.de

Thanks
Daniel

**Comment by glatteis** [comment]
It would be good manners to leave this open until it is fixed (that is what "open" and "closed" are meant for). There are more people that have this problem, see the thread I linked.

**Comment by coltc50** [comment]
+1 me also had this problem...

**Comment by thefriedc** [comment]
Hi,

I wrote an email to the Komoot help almost two months ago without any reply. So I use also this platform as it probably addresses the right people at Komoot.

I am struggling for a long time now to get my BLE device connected with Komoot on my phone. 

I found out that Komoot on a Huawei P10 or Samsung Galaxy S7 does a fine job with connecting. However my Nexus 5X and my newly bought Nokia 8.1 -  running on vanilla Android 8.1 and 9 - are not able to connect to my device. 

Have you experienced any problems with vanilla Android devices and BLE connections?

**Comment by glatteis** [comment]
Yup, my only android phone is running LineageOS, which is basically stock
android.

Am Fr., 25. Okt. 2019 um 11:43 Uhr schrieb thefriedc <
notifications@github.com>:

**Comment by thefriedc** [comment]
Is this a "yes, all good with stock Android" ?

Also had LineageOS 15 on my Nexus - without success connecting.

**Comment by glatteis** [comment]
No, it didn't work for me at all yet D:

thefriedc <notifications@github.com> schrieb am Fr., 25. Okt. 2019, 12:13:

> Is this a "yes, all good with stock Android" ?
>
> Also had LineageOS 15 on my Nexus - without success connecting.
>
>

**Comment by thefriedc** [comment]
To summarize -> **The Android version of Komoot does not run correctly on Android**.

Wow

PS: I also had a try with stock Android 10 - no luck either.

**Comment by glatteis** [comment]
...any updates on this? :)

**Comment by thefriedc** [comment]
> ...any updates on this? :)
@glatteis you mean @danielgard with you question, right?

**Comment by glatteis** [comment]
> > ...any updates on this? :)
> > @glatteis you mean @danielgard with you question, right?

yup yup

**Pull request closed without merging**
